// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERIsST3AkQ8W3SQaTsaVzicYJRkD5NR8',
    appId: '1:569317859981:web:2092a43ec10661260bf8c4',
    messagingSenderId: '569317859981',
    projectId: 'aklatna-6b67f',
    authDomain: 'aklatna-6b67f.firebaseapp.com',
    storageBucket: 'aklatna-6b67f.firebasestorage.app',
    measurementId: 'G-1DZ9182841',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkmyRChLBkOhLJSxpGCmEIa_Y1sGONWe8',
    appId: '1:569317859981:android:2631b47875a1a9930bf8c4',
    messagingSenderId: '569317859981',
    projectId: 'aklatna-6b67f',
    storageBucket: 'aklatna-6b67f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXvsA3zGZbbGZlISjW5MBcGTw9b6Cmcuc',
    appId: '1:569317859981:ios:6b0951e1c07fae7c0bf8c4',
    messagingSenderId: '569317859981',
    projectId: 'aklatna-6b67f',
    storageBucket: 'aklatna-6b67f.firebasestorage.app',
    iosBundleId: 'com.example.aklatna',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXvsA3zGZbbGZlISjW5MBcGTw9b6Cmcuc',
    appId: '1:569317859981:ios:6b0951e1c07fae7c0bf8c4',
    messagingSenderId: '569317859981',
    projectId: 'aklatna-6b67f',
    storageBucket: 'aklatna-6b67f.firebasestorage.app',
    iosBundleId: 'com.example.aklatna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERIsST3AkQ8W3SQaTsaVzicYJRkD5NR8',
    appId: '1:569317859981:web:42ffbf70ff3c4c100bf8c4',
    messagingSenderId: '569317859981',
    projectId: 'aklatna-6b67f',
    authDomain: 'aklatna-6b67f.firebaseapp.com',
    storageBucket: 'aklatna-6b67f.firebasestorage.app',
    measurementId: 'G-R99CE85GGL',
  );
}
